### ISSUE TITLE
images sizes

### ISSUE THREAD

**Issue by jharej** [MM-Lehmann/pptx2h5p#10]
Hello,
we have tested this great tool and discover that h5p files are a lot larger that coresponding pptx files - I can understand why ... Is there an option to set the size of exported images that get included in h5p?
Thanks

**Comment by MM-Lehmann** [comment]
Sorry, No. Currently, they cannot be set and are inherited from the presentation itself. Maybe you can try changing the size of the presentation?

**Comment by MM-Lehmann** [comment]
Apparently, one can set the x/y resolution in the `ppt.Export(file, "PNG", x, y)` call [here](https://github.com/MM-Lehmann/pptx2h5p/blob/904648432febad93ed0f6860e2eec716d3c1f719/pptx2h5p.py#L29).
What would be your preferred Interface to determine the target resolution? Keep in mind, that there is currently no GUI. So IMHO the quick way would be to predetermine a "high" and a "low" resolution mode which can be called with the corresponding bat file.

**Comment by jharej** [comment]
Maybe in some config file in the same directory with the executable, where the default values would be set?

**Comment by MM-Lehmann** [comment]
I've changed the format to `jpg` in the latest release and also added zip compression. Files should be much smaller now.
https://github.com/MM-Lehmann/pptx2h5p/releases/tag/v1.3
