### ISSUE TITLE
Presentations in 4:3 Format

### ISSUE THREAD

**Issue by lasjoh** [MM-Lehmann/pptx2h5p#11]
Hi,
your tool works very nice with 16:9 presentations - but it distorts 4:3 presentations. 
Could you try to fix this and make the tool detect the original ratio?

**Comment by MM-Lehmann** [comment]
At the time of the birth of this tool, h5p demanded slides in 2:1 format and I've included an [aspect ratio fix](https://github.com/MM-Lehmann/pptx2h5p/blob/904648432febad93ed0f6860e2eec716d3c1f719/pptx2h5p.py#L67) to make the result 2:1 by inserting blank spaces if needed. In theory, this should work for 4:3 aspects as well. Can you provide an example where this is not working?

**Comment by MM-Lehmann** [comment]
I've tried with a local drupal/h5p instance and can't reproduce the error. However, after uploading multiple files on [h5p.org](h5p.org), I've hit the same problem, which seems to be stemming from a caching issue (It tried to upload the new config with old images from another file). I would recomment, starting with a fresh browser instance.
Also, check out the new release (v1.3). Maybe the updated toolchain and template format will help as well.
