### ISSUE TITLE
Powerpoint could not be opened

### ISSUE THREAD

**Issue by sreekanths22** [MM-Lehmann/pptx2h5p#12]
Hi 

When I send the PPT to pptx2h5p, I get the following error message:
**Powerpoint could not be opened
(-2147221005, 'Invalid class string', None, None)
An error has occured. Press Enter to close this window.**

Please advise.

- Sreekanth

**Comment by MM-Lehmann** [comment]
Do you have PowerPoint installed?
  

  

  

  
  
  
  
  
>

**Comment by MM-Lehmann** [comment]
Well, PowerPoint is a strict requirement for this tool unfortunately...
  

  

  

  
  
  
  
>

**Comment by sreekanths22** [comment]
Thanks. Will try it out on other systems which has PowerPoint.
