### ISSUE TITLE
Validating h5p package failed.

### ISSUE THREAD

**Issue by lordrylen** [MM-Lehmann/pptx2h5p#15]
I am not sure if this is something on my end or not. 

![Screenshot 2024-07-03 111503](https://github.com/MM-Lehmann/pptx2h5p/assets/25834546/3d883971-f3f9-43be-865d-323376dad216)

**Comment by lordrylen** [comment]
Update: It's on my end. The upload worked on h5p.org.

**Comment by MM-Lehmann** [comment]
Glad to hear!
  

  

  

  
  
  
  
  
>
