### ISSUE TITLE
H5P file in German, how can I change it?

### ISSUE THREAD

**Issue by zuri1337** [MM-Lehmann/pptx2h5p#5]
Hi! First of all, thank you for this great tool, it is helping me a lot.

I have detected that the resulting H5P file is configured in German, for me it is a problem because when I insert a resource the buttons appear in German.

Is there any way that I can modify the default language?

Thank you.

Greetings.

**Comment by MM-Lehmann** [comment]
Hi,
  
I will be working on an update soon.
  
In the meantime, you should be able to change the language settings directly in h5p.
  

  
Regards, Martin
  

  
  
  
  
  
>
