### ISSUE TITLE
h5p uploads broken in latest plugin update

### ISSUE THREAD

**Issue by King1a3** [MM-Lehmann/pptx2h5p#8]
I  found and solved an issue and I thought you may like to know the solution so you can edit your code.

The older h5ps seem to be calling a dependency that has been deprecated.

    1. I changed the filename from "name.h5p" to "name.zip"
    2. Opened it in file explorer (or winzip etc)
    3. Opened h5p.json
    4. removed the first dependency (it seems to have been depreciated) (I compared the *.json file with a newer H5P module)

Line was: {"title": "Phloem coloured", "language": "und", "mainLibrary": "H5P.CoursePresentation", "embedTypes": ["div"], "license": "U", "defaultLanguage": "de", "preloadedDependencies": [**{"machineName": "H5P.Image", "majorVersion": "1", "minorVersion": "1"},** {"machineName": "H5P.CoursePresentation", "majorVersion": "1", "minorVersion": "21"}, {"machineName": "FontAwesome", "majorVersion": "4", "minorVersion": "5"}, {"machineName": "H5P.FontIcons", "majorVersion": "1", "minorVersion": "0"}, {"machineName": "H5P.JoubelUI", "majorVersion": "1", "minorVersion": "3"}, {"machineName": "Drop", "majorVersion": "1", "minorVersion": "0"}, {"machineName": "Tether", "majorVersion": "1", "minorVersion": "0"}, {"machineName": "H5P.Transition", "majorVersion": "1", "minorVersion": "0"}]}

New line: {"title": "Phloem coloured", "language": "und", "mainLibrary": "H5P.CoursePresentation", "embedTypes": ["div"], "license": "U", "defaultLanguage": "de", "preloadedDependencies": [{"machineName": "H5P.CoursePresentation", "majorVersion": "1", "minorVersion": "21"}, {"machineName": "FontAwesome", "majorVersion": "4", "minorVersion": "5"}, {"machineName": "H5P.FontIcons", "majorVersion": "1", "minorVersion": "0"}, {"machineName": "H5P.JoubelUI", "majorVersion": "1", "minorVersion": "3"}, {"machineName": "Drop", "majorVersion": "1", "minorVersion": "0"}, {"machineName": "Tether", "majorVersion": "1", "minorVersion": "0"}, {"machineName": "H5P.Transition", "majorVersion": "1", "minorVersion": "0"}]}

     5. deleted the bold text, then saved the changes and closed the file.
    6. changed "name.zip" back into "name.h5p" and uploaded it. Works fine now.

By the way, Thankyou so-much for this software, it has saved me so much time!

**Comment by King1a3** [comment]
I Think you may only need to edit the template.h5p

**Comment by King1a3** [comment]
by the way 
Moodle 3.11.4 (Build: 20211108)
H5P 1.22.4 (plugin for moodle)

Running on Docker: bitnami/moodle:latest

However my university has the same issue as well.

Sam

**Comment by MM-Lehmann** [comment]
Thanks for digging this up. When I find the time, I will make a test between those two versions.

**Comment by King1a3** [comment]
I have been trying to compile the code with my differnt version of the h5p.json and It won't work. 
do you compile the pptx2h5p.py? or the .spec?

**Comment by King1a3** [comment]
any tips?

**Comment by MM-Lehmann** [comment]
Take pyinstaller and compile the .spec

**Comment by King1a3** [comment]
Thanks!

**Comment by Ron7421** [comment]
Hi, same problem here, would be very grateful is this would be solved, sadly enough i can't :(

thnx

**Comment by nickcfu** [comment]
I have edit the .json file as @King1a3 find, BUT I got "Error writing to database" after the save.

Running on Moodle 3.11.9

Anyone found a solution? or an update ?

The first error that I got without any edition on H5P file is:
"You're trying to upload content of an older version of H5P. Please upgrade the content on the server it originated from and try to upload again or turn on the H5P Hub to have this server upgrade it for your automaticall."

**Comment by MM-Lehmann** [comment]
You could try to replace the template by any h5p file downloaded from your instance, hoping that nothing changed under the hood concerning this tool.
  
Sorry, i won't have time to look deeper for the next few weeks.
  

  

  
  
  
  
  
>

**Comment by MM-Lehmann** [comment]
I've updated the toolchain and template config from a fresh download off of h5p.org. It should be inline with your findings. Check it out: https://github.com/MM-Lehmann/pptx2h5p/releases/tag/v1.3

**Comment by King1a3** [comment]
Cheers,
Your tool is great!
