### ISSUE TITLE
Paquet invalide

### ISSUE THREAD

**Issue by ericfalcon** [MM-Lehmann/pptx2h5p#9]
Bonjour
Sur windows 11 et office 365, lorsque j'utilise votre outil et que j'importe le H5P créé dans ma plateforme moodle, cela me dit que c'est un paquet invalide.

**Comment by MM-Lehmann** [comment]
I am sorry, Windows 11 is currently not supported
  

  

  

  
  
  
  
  
>

**Comment by ericfalcon** [comment]
Je l'ai mis en mode de compatibilité windows 8, il me semble que cela à fonctionner.

**Comment by MM-Lehmann** [comment]
I just tested it on Windows 11 23H2 and it worked with a recent .pptx file. I've also uploaded it to h5p.org without any errors. Could you please provice a minimal example to reproduce the error? Also, which version of moodle/h5p are you using? There might be version conflicts. 
You could always try an older release of this tool for older versions of moodle.

**Comment by MM-Lehmann** [comment]
Try the new release, it should get rid of any errors.
